// Form ActionType
export const SHOW_FORM_AcT = "SHOW_FORM_AcT";
export const CLOSE_FORM_AcT = "CLOSE_FORM_AcT";
//Account ActionType
export const FETCH_LIST_ACCOUNT = "FETCH_LIST_ACCOUNT";
export const DELETE_ACCOUNT = "DELETE_ACCOUNT";
export const TOGLE_FORM_UPATE = "TOGLE_FORM_UPATE";
export const FETCH_ACCOUNT_UPDATE_INFO = "FETCH_ACCOUNT_UPDATE_INFO";

//Product ActionType
export const FETCH_LIST_PRODUCT = "FETCH_LIST_PRODUCT";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const FETCH_PRODUCT_UPDATE_INFO = "FETCH_PRODUCT_UPDATE_INFO";
// Category ActionType
export const FETCH_LIST_CATEGORY = "FETCH_LIST_CATEGORY";
export const DELETE_CATEGORY = "DELETE_CATEGORY";
export const FETCH_CATEGORY_UPDATE_INFO = "FETCH_CATEGORY_UPDATE_INFO";
